### ISSUE TITLE
Problem in plotting ms - neuromag

### ISSUE THREAD

**Issue by tavellaa** [plus-microstate/toolbox#11]
Dear all,
I have an issue in plotting ms from MEG data, I think there is a problem with the neuromag306 template but I am not able to get over it.
I preprocessed my data with brainstorm and used the import_brainstorm function as well, microstate estimate was ok.
I attach the figure it comes from the plot function and my workspace. Labels are in the same order of data channel file.
Can someone take a look and see what's wrong? Thank you in advance.

Download attached files from here:
https://unibari-my.sharepoint.com/:u:/g/personal/a_tavella1_studenti_uniba_it/ESq2guRe75NJhg209tXpMhMB3fa6AJvdOQaFRnBoqAyJ7g?e=ydpSGZ

**Comment by lukewtait** [comment]
Hi, I'm on annual leave this week but will address this next week. Good news is I suspect this is a problem I am aware of and hopefully a quick fix (with permanent fix coming in the next toolbox release). Best, Luke Tait.
________________________________
From: tavellaa ***@***.***>
Sent: Wednesday, November 16, 2022 9:20 AM
To: plus-microstate/toolbox ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [plus-microstate/toolbox] Problem in plotting ms - neuromag (Issue #11)

External email to Cardiff University - Take care when replying/opening attachments or links.
Nid ebost mewnol o Brifysgol Caerdydd yw hwn - Cymerwch ofal wrth ateb/agor atodiadau neu ddolenni.



Dear all,
I have an issue in plotting ms from MEG data, I think there is a problem with the neuromag306 template but I am not able to get over it.
I preprocessed my data with brainstorm and used the import_brainstorm function as well, microstate estimate was ok.
I attach the figure it comes from the plot function and my workspace. Labels are in the same order of data channel file.
Can someone take a look and see what's wrong? Thank you in advance.

Download attached files from here:
https://unibari-my.sharepoint.com/:u:/g/personal/a_tavella1_studenti_uniba_it/ESq2guRe75NJhg209tXpMhMB3fa6AJvdOQaFRnBoqAyJ7g?e=ydpSGZ<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Funibari-my.sharepoint.com%2F%3Au%3A%2Fg%2Fpersonal%2Fa_tavella1_studenti_uniba_it%2FESq2guRe75NJhg209tXpMhMB3fa6AJvdOQaFRnBoqAyJ7g%3Fe%3DydpSGZ&data=05%7C01%7Ctaitl2%40cardiff.ac.uk%7Ca34d044f8923496e6a6408dac7b3e0a6%7Cbdb74b3095684856bdbf06759778fcbc%7C1%7C0%7C638041872618825953%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YOGm781sqZ27vGCJGU9IDCG2z44n3LDE97jbv11uR8I%3D&reserved=0>

**Comment by lukewtait** [comment]
Hi, I have added a fix to +microstate for this bug. If you type "microstate.functions.install" into your command line, your +microstate version should update to v1.7. Hopefully this will have fixed your bug with plotting the Neuromag system. Thanks, Luke Tait.
________________________________
From: tavellaa ***@***.***>
Sent: Wednesday, November 16, 2022 9:20 AM
To: plus-microstate/toolbox ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [plus-microstate/toolbox] Problem in plotting ms - neuromag (Issue #11)

External email to Cardiff University - Take care when replying/opening attachments or links.
Nid ebost mewnol o Brifysgol Caerdydd yw hwn - Cymerwch ofal wrth ateb/agor atodiadau neu ddolenni.



Dear all,
I have an issue in plotting ms from MEG data, I think there is a problem with the neuromag306 template but I am not able to get over it.
I preprocessed my data with brainstorm and used the import_brainstorm function as well, microstate estimate was ok.
I attach the figure it comes from the plot function and my workspace. Labels are in the same order of data channel file.
Can someone take a look and see what's wrong? Thank you in advance.

Download attached files from here:
https://unibari-my.sharepoint.com/:u:/g/personal/a_tavella1_studenti_uniba_it/ESq2guRe75NJhg209tXpMhMB3fa6AJvdOQaFRnBoqAyJ7g?e=ydpSGZ<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Funibari-my.sharepoint.com%2F%3Au%3A%2Fg%2Fpersonal%2Fa_tavella1_studenti_uniba_it%2FESq2guRe75NJhg209tXpMhMB3fa6AJvdOQaFRnBoqAyJ7g%3Fe%3DydpSGZ&data=05%7C01%7Ctaitl2%40cardiff.ac.uk%7Ca34d044f8923496e6a6408dac7b3e0a6%7Cbdb74b3095684856bdbf06759778fcbc%7C1%7C0%7C638041872618825953%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YOGm781sqZ27vGCJGU9IDCG2z44n3LDE97jbv11uR8I%3D&reserved=0>
