### ISSUE TITLE
how to create a layout with other brain atlases

### ISSUE THREAD

**Issue by HuibangTan** [plus-microstate/toolbox#12]
Dear Luke,

The problem I encountered was that my source data was parcellated using the AAL2 atlas which is not contained in the toolbox. How can I create a layout with other brain atlases? 
Looking forward for your replay!

Thanks,
Huibang

**Comment by plus-microstate** [comment]
Hi Huibang, 

Thanks for your interest in the toolbox! Unfortunately there is no "standardized" way to do this for source data. For the pre-existing atlases in the toolbox, I have used a downsampled version of Fieldtrip's template anatomy for generating these layouts. Hence, if you want to use the cohort.plot or individual.plot functions you'll need to align your atlas to the downsampled inflated surface that is included with the toolbox. If your atlas is in Fieldtrip format (or can be converted into Fieldtrip format by Fieldtrip's ft_read_atlas function), then the code to do this alignment (using the AAL atlas as an example) can be found here: https://github.com/plus-microstate/toolbox/raw/12-how-to-create-a-layout-with-other-brain-atlases/create-layout-atlas.zip. Just download and unzip the folder, and run the script make_layout.m. You'll need to have Fieldtrip installed. 

Thanks,
Luke
