### ISSUE TITLE
Example data files not loading

### ISSUE THREAD

**Issue by plus-microstate** [plus-microstate/toolbox#2]
**Reported via email**

When trying to load the .mat file "example1_data.mat" the following error message is received: 

```
Error using load
Unable to read MAT-file
PATH/toolbox-master/examples/example1_EEGcanonicalmaps/example1_data.mat.
Not a binary MAT-file. Try load -ASCII to read as text
```

**Comment by lukewtait** [comment]
I've found the cause of the issue, and I'm working on a solution. In the meantime, a temporary workaround is now given in the [Wiki](https://github.com/plus-microstate/toolbox/wiki/Download-and-Install#downloading-the-tutorial-data-and-other-mat-files).

**Comment by lukewtait** [comment]
Ok, this has now been solved. The simplest way to fix the problem would be to completely delete the toolbox-master folder and redownload it as before. Follow the same steps to install it, adding it to the path etc. There is one extra step now, which is to run `microstate.functions.install`. Full documentation for installation is updated on the homepage and the Wiki (linked above).
