### ISSUE TITLE
EGI template

### ISSUE THREAD

**Issue by ABnormalJR** [plus-microstate/toolbox#4]
Hi how I can create an EGI template, particularly the GSN-HydroCel-129.sfp? as it is not in standard eeg1020? thanks!

**Comment by plus-microstate** [comment]
Hi there, 

Sorry, this issue completely slipped by me! Did you sort this in the end (I had someone contact me by email about templates, so I just wanted to check if this is the same person or a separate issue)?

Best,
Luke
