### ISSUE TITLE
Error in tutorial 1

### ISSUE THREAD

**Issue by suhasmvg** [plus-microstate/toolbox#6]
_Good day! @lukewtait, @plus-microstate

I was exploring the +microstate starting from tutorial 1. While running the following section,_ 

Analyse and visualise the microstate data
% Call layout creator from the command line
template = 'eeg1020' ; % Use the EEG 10-20 system template
labels = {'Fp2';'Fz';'Fp1';'F3';'F7';'C3';'T3';'P3';'T5';'Pz';...
          'O1';'Oz';'O2';'P4';'T6';'C4';'T4';...
          'F8';'F4';'Cz'} ; % equivalent to data.label
layout = microstate.functions.layout_creator(template,labels) ; 

_Ran into an error!_

Error using load
Unable to read MAT-file C:\Program
Files\MATLAB\R2022a\toolbox\toolbox-master\toolbox-master\+microstate\+external\fieldtrip\template\layout\EEG1005.mat. Not a binary MAT-file. Try load -ASCII to read as text.

Error in microstate.functions.layout_creator (line 60)
            tmplayout = load(fullfile(mspath,'+external','fieldtrip','template',dir,file)) ;

_Unable to identify where the error is or am I missing something. Please help!_

**Comment by lukewtait** [comment]
Hi, thanks for letting me know about this. It looks like there is a problem with finding the toolbox path. Could you please check what the output of typing the following into the console says: 

`mspath=microstate.functions.toolbox_path`

And could you validate that this is the correct location for the toolbox? 

Could you also try this line code of code, and let me know the output please? 

`fullfile('hello','+world')`

My guess based on your error message is that there is an issue with `fullfile` where it is deleting the backslash if a plus symbol is included, so while the output of the above line should be `hello\+world` I suspect it might read `hello+world`. If that is the case, I'll have a dig into the `fullfile` documentation to see if this has changed in R2022.

**Comment by suhasmvg** [comment]
Hi again @lukewtait 
mspath=microstate.functions.toolbox_path indicates right path to the toolbox. Also rest of the initial code from tutorial is working fine in fetching the data upto "Perform microstate analysis". The error is thrown in "Analyse and visualise the microstate data" stage. If the problem was with finding the toolbox path, none of the code should have run isn't it?

Here is the result of running: 
>> fullfile('hello','+world')

ans =

    'hello\+world'

**Comment by lukewtait** [comment]
Ok, I've just noticed that the Github formatting might have confused me in the last message! Could you confirm that in your error message, there are backslashes before the + signs in the path to the file (i.e. "Unable to read MAT-file...")? I think Github formatting interprets \\+ as +, so in the version of the error message you posted these backslashes disappeared, which made me think there was an issue with fullfile when that seems to be fine. 

Looking at your error message again, my guess would be that the EEG1005.mat file didn't download properly. Did you run `microstate.functions.install` when you first downloaded the toolbox? This will download and install all required .mat files. If you didn't run this, please do so and it should hopefully fix the issue (You'll know if it is working as you should get a series of messages saying "Downloading file https://github.com/plus-microstate/toolbox..." etc with each full file name) . 

If you did already run the install function, you won't get the "Downloading file" messages and the file must have been corrupted. You can either try downloading that one file again from [here](https://github.com/plus-microstate/toolbox/blob/master/%2Bmicrostate/%2Bexternal/fieldtrip/template/layout/EEG1005.mat), making sure to move it to the right folder (the folder in your error message), or completely delete and reinstall the toolbox.

**Comment by suhasmvg** [comment]
Probably I missed running `microstate.functions.install` . Now all the files are downloaded after running it, no more errors. Sorry! my bad! Extremely grateful for your valuable time!!

**Comment by lukewtait** [comment]
No problem, you're welcome! Thanks very much for bringing this to my attention, doing so will always help us improve the toolbox! For the next version, I'll take a look and see if there is a way to automatically detect if someone needs to run the install function or give more useful error messages if they have not. I'm closing the issue now, but please feel free to contact me again if you run into any more problems.
